export const categoryMap = {
  "Аксесуари": "Apparel & Accessories",
  "Балетки та мокасини": "Apparel & Accessories > Shoes > Flats",
  "Блузи та сорочки": "Apparel & Accessories > Clothing > Clothing Tops > Blouses",
  "Босоніжки": "Apparel & Accessories > Shoes > Sandals",
  "Верхній одяг": "Apparel & Accessories > Clothing > Outerwear",
  "Гаманці": "Apparel & Accessories > Handbags, Wallets & Cases > Wallets & Money Clips > Wallets",
  "Головні убори": "Apparel & Accessories > Clothing Accessories > Headwear",
  "Джинси": "Apparel & Accessories > Clothing > Pants > Jeans",
  "Жіноче взуття": "Apparel & Accessories > Shoes",
  "Жіночий одяг": "Apparel & Accessories > Clothing",
  "Клатчи": "Apparel & Accessories > Handbags, Wallets & Cases > Handbags > Clutch Bags",
  "Кросівки та кеди": "Apparel & Accessories > Shoes > Sneakers",
  "Мокасини": "Apparel & Accessories > Shoes > Flats",
  "Одяг": "Apparel & Accessories > Clothing",
  "Оксфорди та лофери": "Apparel & Accessories > Shoes > Flats",
  "Портмоне": "Apparel & Accessories > Handbags, Wallets & Cases > Wallets & Money Clips",
  "Піджаки": "Apparel & Accessories > Clothing > Outerwear > Coats & Jackets",
  "Ремені": "Apparel & Accessories > Clothing Accessories > Belts",
  "Ремені та пояси": "Apparel & Accessories > Clothing Accessories > Belts",
  "Рукавички": "Apparel & Accessories > Clothing Accessories > Gloves & Mittens",
  "Рюкзаки": "Apparel & Accessories > Handbags, Wallets & Cases > Handbags",
  "Сабо та мюлі": "Apparel & Accessories > Shoes > Sandals",
  "Саквояжи": "Apparel & Accessories > Handbags, Wallets & Cases > Handbags",
  "Сандалії": "Apparel & Accessories > Shoes > Sandals",
  "Светри та джемпери": "Apparel & Accessories > Clothing > Clothing Tops > Sweaters",
  "Світшоти та кофти": "Apparel & Accessories > Clothing > Clothing Tops > Sweatshirts",
  "Сорочки": "Apparel & Accessories > Clothing > Clothing Tops > Shirts",
  "Спортивні костюми": "Apparel & Accessories > Clothing > Activewear",
  "Спідниці": "Apparel & Accessories > Clothing > Skirts",
  "Сукні та сарафани": "Apparel & Accessories > Clothing > Dresses",
  "Сумки": "Apparel & Accessories > Handbags, Wallets & Cases > Handbags",
  "Туфлі": "Apparel & Accessories > Shoes > Heels",
  "Футболки": "Apparel & Accessories > Clothing > Clothing Tops > T-Shirts",
  "Футболки та поло": "Apparel & Accessories > Clothing > Clothing Tops",
  "Черевики": "Apparel & Accessories > Shoes > Boots",
  "Черевики та ботильйони": "Apparel & Accessories > Shoes > Boots",
  "Чоботи": "Apparel & Accessories > Shoes > Boots",
  "Чоловіче взуття": "Apparel & Accessories > Shoes",
  "Чоловічий одяг": "Apparel & Accessories > Clothing",
  "Шльопанці та в'єтнамки": "Apparel & Accessories > Shoes > Sandals",
  "Шорти": "Apparel & Accessories > Clothing > Shorts",
  "Штани та брюки": "Apparel & Accessories > Clothing > Pants"
}
